"""
Consolidate 5 unit submissions into a single affiliate P&L Excel workbook.
P&L structure:
  Net Sales                 (sum of 3 Sales units)
  Distribution Margin       (sum of 3 Sales units)
  Total R&D                 (from R&D unit)
  Marketing                 (from General Admin)
  Other Advertising & Promotion (from General Admin)
  Sales Force               (from General Admin)
  General Admin             (from General Admin)
  Total SG&A                (sum of SG&A lines)
  Division Margin           = Distribution Margin - Total R&D - Total SG&A
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

NAVY   = "1F3864"
BLUE   = "2E5FA3"
TEAL   = "00B8A0"
LGREY  = "F2F4F8"
WHITE  = "FFFFFF"
RED_T  = "C0392B"
GREEN_T= "1A6B3C"

PNL_ORDER = [
    ("Net Sales",                      "total",  False),
    ("Distribution Margin",            "total",  False),
    ("Total R&D",                      "total",  True),   # cost = positive = unfav
    ("Marketing",                      "detail", True),
    ("Other Advertising and Promotion","detail", True),
    ("Sales Force",                    "detail", True),
    ("General Admin",                  "detail", True),
    ("Total SG&A",                     "total",  True),
    ("Division Margin",                "total",  False),
]

COLS = ["LBE FY2026", "Prior LBE", "Var vs Prior LBE",
        "Budget FY2026", "Var vs Budget",
        "Prior Year (FY2025)", "Var vs Prior Year"]

def consolidate(unit_data_list: list, output_path: str) -> dict:
    """
    unit_data_list: list of dicts from excel_parser.parse_unit_file()
    Returns consolidated values dict for use by other agents.
    """
    # Merge all lines from all units (sum where same line appears in multiple units)
    merged = {}
    for unit in unit_data_list:
        for line, vals in unit["lines"].items():
            if line not in merged:
                merged[line] = {"lbe": 0, "prior_lbe": 0,
                                "budget": 0, "prior_year": 0}
            for k in ["lbe", "prior_lbe", "budget", "prior_year"]:
                merged[line][k] = round(merged[line][k] + vals.get(k, 0), 1)

    # Compute Division Margin
    dm  = merged.get("Distribution Margin", {})
    rd  = merged.get("Total R&D", {})
    sga = merged.get("Total SG&A", {})
    merged["Division Margin"] = {
        k: round(dm.get(k, 0) - rd.get(k, 0) - sga.get(k, 0), 1)
        for k in ["lbe", "prior_lbe", "budget", "prior_year"]
    }

    # Add variance columns
    consolidated = {}
    for line, v in merged.items():
        consolidated[line] = {
            "LBE FY2026":        v["lbe"],
            "Prior LBE":         v["prior_lbe"],
            "Var vs Prior LBE":  round(v["lbe"] - v["prior_lbe"], 1),
            "Budget FY2026":     v["budget"],
            "Var vs Budget":     round(v["lbe"] - v["budget"], 1),
            "Prior Year (FY2025)": v["prior_year"],
            "Var vs Prior Year": round(v["lbe"] - v["prior_year"], 1),
        }

    _write_excel(consolidated, output_path)
    return consolidated


def _write_excel(data: dict, path: str):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Consolidated LBE FY2026"
    ws.sheet_view.showGridLines = False

    thin  = Side(style="thin",   color="C5D0DC")
    med   = Side(style="medium", color=NAVY)
    bdr   = Border(left=thin, right=thin, top=thin, bottom=thin)
    bdr_b = Border(left=thin, right=thin, top=thin, bottom=med)

    def fnt(bold=False, color="1A1A2E", size=10):
        return Font(name="Calibri", bold=bold, size=size, color=color)
    def flll(c): return PatternFill("solid", fgColor=c)
    def aln(h="right"): return Alignment(horizontal=h, vertical="center")

    col_widths = [32, 13, 13, 14, 13, 14, 13, 14]
    for i, w in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    # ── Title ─────────────────────────────────────────────────────────────────
    ws.merge_cells("A1:H1")
    ws["A1"] = "Affiliate Consolidated P&L — LBE FY2026"
    ws["A1"].font = Font(name="Calibri", bold=True, size=14, color=WHITE)
    ws["A1"].fill = flll(NAVY)
    ws["A1"].alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[1].height = 30

    ws.merge_cells("A2:H2")
    ws["A2"] = "Commercial Affiliate  |  Currency: EUR millions  |  Generated by Digital FP&A Manager Agent"
    ws["A2"].font = Font(name="Calibri", size=9, color="5A6A80")
    ws["A2"].fill = flll("EEF2F8")
    ws["A2"].alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[2].height = 16
    ws.row_dimensions[3].height = 8

    # ── Column headers ─────────────────────────────────────────────────────────
    headers = ["P&L Line"] + COLS
    hdr_fills = [NAVY, BLUE, BLUE, TEAL, BLUE, TEAL, BLUE, TEAL]
    for ci, (h, hf) in enumerate(zip(headers, hdr_fills), 1):
        cell = ws.cell(row=4, column=ci, value=h)
        cell.font = fnt(bold=True, color=WHITE, size=10)
        cell.fill = flll(hf)
        cell.alignment = aln("left") if ci == 1 else aln("center")
        cell.border = bdr
    ws.row_dimensions[4].height = 22

    # ── Data ──────────────────────────────────────────────────────────────────
    row = 5
    for (line, ltype, is_cost) in PNL_ORDER:
        if line not in data:
            continue
        vals = data[line]
        is_total  = ltype == "total"
        is_detail = ltype == "detail"
        row_fill  = "F8F9FB" if row % 2 == 0 else WHITE

        # Label
        c = ws.cell(row=row, column=1, value=line)
        c.font = fnt(bold=is_total, color=NAVY if is_total else "1A1A2E")
        c.fill = flll("EEF2F8" if is_total else row_fill)
        c.alignment = Alignment(horizontal="left", vertical="center",
                                indent=0 if is_total else 1)
        c.border = bdr_b if is_total else bdr

        # Numbers
        for ci, col_name in enumerate(COLS, 2):
            c2 = ws.cell(row=row, column=ci)
            v  = vals.get(col_name, 0)
            c2.value = v
            c2.number_format = '#,##0.0;(#,##0.0);"-"'
            c2.alignment = aln("right")
            c2.fill = flll("EEF2F8" if is_total else row_fill)
            c2.border = bdr_b if is_total else bdr

            is_var = "Var" in col_name
            if is_var:
                # Colour variances: for costs, negative var = favourable (green)
                fav = (v > 0 and not is_cost) or (v < 0 and is_cost)
                unfav = (v < 0 and not is_cost) or (v > 0 and is_cost)
                color = GREEN_T if fav else (RED_T if unfav else "1A1A2E")
                c2.font = fnt(bold=is_total, color=color)
            else:
                c2.font = fnt(bold=is_total,
                              color=NAVY if is_total else "1A1A2E")

        ws.row_dimensions[row].height = 18
        row += 1

    # ── Footer ─────────────────────────────────────────────────────────────────
    ws.merge_cells(f"A{row+1}:H{row+1}")
    ws[f"A{row+1}"] = ("Variances: Green = Favourable  |  Red = Unfavourable  |  "
                       "Var vs Prior LBE = LBE minus Prior LBE  |  EUR millions")
    ws[f"A{row+1}"].font = Font(name="Calibri", size=9, italic=True, color="7A8FA8")
    ws[f"A{row+1}"].fill = flll("F8F9FB")

    wb.save(path)
